[versions]
accompanistNavigationAnimation = "0.36.0"
accompanistSwipeRefresh = "0.36.0"
activityCompose = "1.10.1"
androidMaterial = "1.12.0"
androidMaterial3 = "1.3.2"
androidMaterial3Adaptive = "1.1.0"
androidMaterial3AdaptiveNavigation = "1.3.2"
androidRecyclerview = "1.4.0"
androidGradlePlugin = "8.12.1"
androidxArchCoreTesting = "2.2.0"
androidxHiltNavigation = "1.2.0"
androidxBenchmarkJunit4 = "1.3.4"
androidxRecyclerviewSelection = "1.2.0"
androidxTestJunit = "1.2.1"
androidxTestRunner = "1.5.0"
androidxTestUiAutomator = "2.3.0"
androidxUiTooling = "1.8.2"
animation = "1.8.3"
appcompat = "1.7.0"
baselineProfile = "1.3.4"
browser = "1.8.0"
coilCompose = "2.7.0"
chuckerVersion = "4.1.0"

composeShimmer = "1.3.2"
constraintlayout = "2.2.1"
daggerHilt = "2.56.2"
datastorePreferences = "1.1.7"
detekt = "1.23.4"
espresso = "3.6.1"
firebaseAnalyticsKtx = "22.4.0"
firebaseCore = "21.1.1"
firebaseCrashlytics = "19.4.3"
firebaseCrashlyticsGradle = "3.0.3"
firebasePerf = "21.0.5"
firebasePerfGradlePlugin = "1.4.2"
flexbox = "3.0.0"

gmsPlugin = "4.4.2"
hiltCompiler = "1.2.0"
hiltAndroidTesting = "2.56.2"
hiltWork = "1.2.0"
jsoup = "1.20.1"
junit = "4.13.2"
ktlint = "12.3.0"
kotlin = "2.1.21"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
ksp = "2.1.21-2.0.1"
ktx = "1.16.0"
leakcanaryAndroid = "2.14"
legacySupportV4 = "1.0.0"
lifecycleViewmodelCompose = "2.9.0"
mockitoCore = "5.18.0"
mockitoKotlin = "5.4.0"
okhttp = "5.3.2"
navigationCompose = "2.8.5"
kotlinxSerializationJson = "1.7.3"
materialIconsExtended = "1.7.8"
moshi = "1.15.2"
pagingRuntimeKtx = "3.3.6"
preferenceKtx = "1.2.1"
profileinstaller = "1.4.1"
retrofit = "3.0.0"
retrofit2KotlinCoroutinesAdapter = "0.9.2"
robolectric = "4.16"
room = "2.7.1"
runtimeLivedata = "1.9.0"
testHarness = "0.36.0"
timber = "5.0.1"
uiTestManifest = "1.8.2"
workRuntimeKtx = "2.10.3"
workTesting = "2.10.1"
turbine = "1.0.0"

[libraries]
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanistNavigationAnimation" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwipeRefresh" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
android-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltNavigation" }
androidx-adaptive-navigation-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation-android", version.ref = "androidMaterial3Adaptive" }
android-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
android-hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompiler" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
android-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidMaterial3" }
android-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "androidMaterial3Adaptive" }
android-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "androidMaterial3Adaptive" }
android-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "androidMaterial3Adaptive" }
android-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "androidMaterial3AdaptiveNavigation" }
android-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidRecyclerview" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCoreTesting" }
androidx-benchmark-macrobenchmark-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidxBenchmarkJunit4" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxTestUiAutomator" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxUiTooling" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxUiTooling" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref ="chuckerVersion" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref ="chuckerVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebasePerf" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "daggerHilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleViewmodelCompose" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelCompose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelCompose" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3-window-size-classes = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidMaterial3" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "androidxRecyclerviewSelection" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlin-coroutines-adapter = { module = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter", version.ref = "retrofit2KotlinCoroutinesAdapter" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
test-harness = { module = "com.google.accompanist:accompanist-testharness", version.ref = "testHarness" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf-gradle = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfGradlePlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
baseline-profiles = { id = "androidx.baselineprofile", version.ref = "baselineProfile" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
